---
version: '3'

dotenv: ['.env']

tasks:
  encrypt:
    desc: Encrypt files using SOPS
    preconditions:
      - sh: test -f .env
        msg: ".env file doens't exist"
    cmds:
      - sops -e --input-type dotenv --output-type dotenv .env > .env.enc

  decrypt:
    desc: Decrypt files using SOPS
    preconditions:
      - sh: test -f .env.enc
        msg: ".env.enc doesn't exist"
    cmds:
      - sops -d --input-type dotenv --output-type dotenv .env.enc > .env

  coverage:
    desc: Run tests and generate coverage report (stdout summary)
    cmds:
      - cargo llvm-cov --all-features --workspace --summary-only --fail-under-lines 90

  coverage:report:
    desc: Run tests and generate LCOV coverage report (for Coveralls)
    cmds:
      - cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info --fail-under-lines 90

  test:coverage:
    desc: Run tests and generate HTML coverage report
    cmds:
      - cargo llvm-cov --all-features --workspace --html
      - echo "HTML report generated in target/llvm-cov/html/index.html"

  coverage:upload:
    desc: Upload coverage report to Coveralls
    precondition:
      - sh: test -f lcov.info
        msg: "lcov.info doesn't exist"
    cmds:
      - /usr/local/bin/coveralls report lcov.info  -n -r {{ .COVERALLS_REPO_TOKEN }}

  test:
    desc: Run tests
    cmds:
      - task: fmt:check
      - task: clippy
      - cargo test --profile ci
  test:ci:
    desc: Run tests using the CI profile
    cmds:
      - task: test

  fmt:
    desc: Format code with rustfmt
    cmds:
      - cargo fmt --all

  fmt:check:
    desc: Check code formatting with rustfmt
    cmds:
      - cargo fmt -- --check

  init:
    desc: Initialize
    preconditions:
      - test -f config.toml.example
    cmds:
      - cp config.toml.example config.toml

  lint:
    desc: Run all linting checks
    cmds:
      - task: clippy

  clippy:
    desc: Run cargo clippy
    cmds:
      - cargo clippy --workspace --all-targets --all-features -- -D warnings

  default:
    cmds:
      - task -l
  deps:
    desc: Install dependencies
    cmds:
      - cargo install cross --git https://github.com/cross-rs/cross

  build:
    desc: Build the project for all supported architectures
    cmds:
      - task: build:amd64
      - task: build:arm64

  build:armv7:
    desc: Build for ARMv7
    cmds:
      - cross build --release --target armv7-unknown-linux-gnueabihf

  build:amd64:
    desc: Build for AMD64
    cmds:
      - cross build --release --target x86_64-unknown-linux-gnu

  build:arm64:
    desc: Build for ARM64
    cmds:
      - cross build --release --target aarch64-unknown-linux-gnu

  build:local:
    desc: Build for current architecture
    cmds:
      - cargo build --release

  run:
    desc: Run the MCP Server
    cmds:
      - cargo run

  docker:build:
    desc: Build the Docker image
    cmds:
      - docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t rescue-groups-mcp .

  docker:run:
    desc: Run the Docker image
    cmds:
      - docker run --rm -i rescue-groups-mcp

  clean:
    desc: Clean build artifacts
    cmds:
      - cargo clean
