---
version: '3'

tasks:
  test:
    desc: Run tests
    cmds:
      - cargo test --profile ci
      - cargo fmt --all --check
  init:
    desc: Initialize
    preconditions:
      - test -f config.toml.example
    cmds:
      - cp config.toml.example config.toml
  lint:
    desc: Lint
    cmds:
      - task: clippy
  clippy:
    desc: Run cargo clippy
    cmds:
      - cargo clippy --workspace --all-targets --all-features -- -D warnings

  fmt:
    desc: Rust fmt
    cmds:
      - cargo fmt
  default:
    cmds:
      - task -l
  deps:
    desc: Install dependencies
    cmds:
      - cargo install cross --git https://github.com/cross-rs/cross

  build:
    desc: Build the project for all supported architectures
    cmds:
      - task: build:amd64
      - task: build:arm64

  build:armv7:
    desc: Build for ARMv7
    cmds:
      - cross build --release --target armv7-unknown-linux-gnueabihf

  build:amd64:
    desc: Build for AMD64
    cmds:
      - cross build --release --target x86_64-unknown-linux-gnu

  build:arm64:
    desc: Build for ARM64
    cmds:
      - cross build --release --target aarch64-unknown-linux-gnu

  build:local:
    desc: Build for current architecture
    cmds:
      - cargo build --release

  run:
    desc: Run the MCP Server
    cmds:
      - cargo run

  docker:build:
    desc: Build the Docker image
    cmds:
      - docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t rescue-groups-mcp .

  docker:run:
    desc: Run the Docker image
    cmds:
      - docker run --rm -i rescue-groups-mcp

  clean:
    desc: Clean build artifacts
    cmds:
      - cargo clean
